all: true
dir: "{{.InterfaceDir}}/mocks/{{ snakecase .InterfaceName }}_mock"
filename: "mock.go"
pkgname: "mock_{{ snakecase .InterfaceName }}"
structname: "{{.InterfaceName}}"
force-file-write: true
formatter: goimports
log-level: info
recursive: true
require-template-schema-exists: true
template: testify
packages:
  github.com/taninchot-work/backend-challenge: